name = "GlorpCraft"
author = "Dimond_person"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd73b16631f4a93ab84cd17ff6c8517c6cd215030d9407c3d9e22ac8fe8a6614"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
