name = "GlorpCraft"
author = "Dimond_person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a17bc8b6a61290b2ba7ddc3e774a3aac0f63ec056329fc6a5c7f36deeacb7121"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
