name = "GlorpCraft"
author = "Dimond_person"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d927cea15001bff2f8dab0de2536ce4c750c990f8d4c1d5f8e069b4c748e79a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
